### ISSUE TITLE
Crashing issue and question about commands

### ISSUE THREAD

**Issue by Lunaraia** [t-larson/BaseMod#10]
as the title says the game just randomly crashes with the  new update it just happens without any rhyme or reason, once in combat,  twice in the store and a fourth time on the map itself.

As for the question I can't get the "Deck r" command to work as the  id's required aren't posted anywhere, I tried using the card name and  also number for the card in my deck, based on placement, but it just  didn't work, am I missing something obvious or does it have a specific  ID?

**Comment by daviscook477** [comment]
Can you post the log for ModTheSpire so we can see what's crashing? Also for now there isn't a list of card ids but for the most part a card like "Survivor" would have an I'd of "Survivor". Eventually an id list will exist.

**Comment by daviscook477** [comment]
Take a look here for some of the ids: .https://github.com/t-larson/BaseMod/issues/4 There are going to be some crashes since there was just a patch to the base game so any crash logs you can give would be really helpful! Thanks

**Comment by Lunaraia** [comment]
[hs_err_pid15512.log](https://github.com/t-larson/BaseMod/files/1731938/hs_err_pid15512.log)
[hs_err_pid13788.log](https://github.com/t-larson/BaseMod/files/1731939/hs_err_pid13788.log)

here are a few hope they help -^_^-

**Comment by daviscook477** [comment]
Is there any chance you're running an older version of java on your computer? MoTheSpire requires at least 1.8

**Comment by daviscook477** [comment]
And you said these crashes happen in the middle of the game? Not during loading?

**Comment by Lunaraia** [comment]
middle of combat, while buying stuff at the store while on the map screen, unless there are loading zones in those areas after you are able to start doing stuff on them there were no loading involved, although the crash at the store did happen while trying to remove a Block.

I had Java version 8.151 checked for updates and found version 8.161, installed that in case that was what was causing it.

**Comment by daviscook477** [comment]
Okay then that's probably not what's causing it. I'm just having trouble making heads or tails out of this crash log. Let me see what other ideas I might have

**Comment by daviscook477** [comment]
I looked into the error some more and it seems like a crash related to the JVM rather than mod code. My current ideas are that maybe the modloader is running the game with an insufficient amount of RAM or that you need to run the windows registry repair tool.

**Comment by daviscook477** [comment]
There might be a chance this is caused by some sort of memory leak in the mods that is causing a system call for extra memory allocation to fail. I might have to profile the game to make sure it's not using too many resources

**Comment by Lunaraia** [comment]
just tried again with the newest java and the game crashed in the middle of combat here is the log in case it helps pinpointing the error

[hs_err_pid4024.log](https://github.com/t-larson/BaseMod/files/1732037/hs_err_pid4024.log)

**Comment by daviscook477** [comment]
Silly question but are you sure you're running the latest version of BaseMod? Since the patch week 12 dropped a bunch of things would break if you didn't update

**Comment by Lunaraia** [comment]
I downlaoded the latest one because the one before that simply refused to work for me XD I only stated to attempt modding this game yesterday and that old version was busted soo.... pretty damn sure

**Comment by daviscook477** [comment]
I'm sorry I can't seem to figure out a solution. The exception is being thrown in native code as a part of the rendering method. Are you doing any graphics stuff?

**Comment by t-larson** [comment]
What graphics card do you have?

**Comment by Lunaraia** [comment]
will try that stay tuned for info on wether it works or not

**Comment by Lunaraia** [comment]
I have a GTX 750 TI however after swapping to 64-bit it seems to have fixed the issue been running for better part of an hour now with no issues

**Comment by Lunaraia** [comment]
finished 2 entire sessions without a crash, Issue was 32-Bit Java, Issue is closed for me
