### ISSUE TITLE
Clicking on the Mod Badges

### ISSUE THREAD

**Issue by daviscook477** [t-larson/BaseMod#7]
So apparently after I fixed clicking on mod badges I broke it again and this time I don't know how. I'll work on fixing it but I'm not really sure why the Hitbox would be throwing the hover event and having hover text but simultaneously be refusing to change its clicked variable to true. Any ideas?

**Comment by daviscook477** [comment]
Figured out the reason. There was a hotfix today that changed line numbers in CardCrawlGame. I'll set a pull request with a fix eventually.

**Comment by t-larson** [comment]
I'm guessing a fix for this was included in the last bunch of changes I merged in, seems to be working fine on my end.
