### ISSUE TITLE
BaseMod no longer functional after patch?

### ISSUE THREAD

**Issue by polynomnom** [t-larson/BaseMod#9]
Hi, just updated to the latest files and version of the game, but the mod is no longer functional. The mod settings menu will not open, nor will the default console key open the console

**Comment by daviscook477** [comment]
The window being opened and displaying the log for the game is an intended change. The reason that BaseMod is not working with the most recent version of the game is that the devs changed up some of the files which makes the patches that BaseMod does not work properly. There should be a fix up soon.

**Comment by polynomnom** [comment]
Ah, Alright thank you

**Comment by polynomnom** [comment]
Will there be a new release or will the current version be updated

**Comment by daviscook477** [comment]
There will be a new release. For the meantime go ahead and use this release: https://github.com/daviscook477/BaseMod/releases/tag/v1.6.1

**Comment by t-larson** [comment]
Should be fixed in the latest release.
